#!/usr/bin/env bash 


# given an executable, regress through the test cases. 


CMD="$1" ; shift; 
if [ "$CMD" == "" ] ; then 
	CMD="explodie"
fi

echo "TAP version 13";  # why not be right? 
echo "1..N";

#if [ ! -e "$CMD" ] ; then  
#	echo "Bail out!"
#	echo "  the cmd ($CMD) does not seem to exist, quiting\n"
#	exit 2;
#fi

FAIL="no"

for i in testcases/explodie.*.lumped
do
	# echo $i 

	$CMD $i | sort > $i.test.out
        RC="$?"

        if [ "0" != "$RC" ] ; then
                echo "Bail out! # ($CMD) returned not okay ($RC)" 
                exit 2;
        fi

	J=$(echo $i | sed "s/lumped/exploded/g") 
	#  echo "result file ($J)"	
	
	if [ -f $J ] ; then 
		sort $J > $J.exemplar.out 
		if diff -u $J.exemplar.out $i.test.out  > $i.test.out.diff
		then
			echo "ok # $i"
		else
			echo "not ok # $i see diff"  
			FAIL="yes"
			cat $i.test.out.diff | sed "s/^/  /g"
		fi
	else 
		echo "not ok # $i "
		echo "   The test case failed ... there is no exploded file"
		FAIL="yes"
	fi

	# rm $i.test.out

done

if [ "yes" == "$FAIL" ] ; 
then 
	exit 1 
else 
	exit 0	
fi


